# Control file for continuous integration testing at http://travis-ci.org/
language: cpp
dist: trusty

matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
            - pkg-config
            - libncurses5-dev
            - libncursesw5-dev
            - zlib1g-dev 
            - libssl-dev
            - liblz4-dev
            - libcurl4-openssl-dev 
            - liblz-dev
            - libbz2-dev
            - liblzma-dev
      env:
         - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"
      compiler: gcc

    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - pkg-config
            - libncurses5-dev
            - libncursesw5-dev
            - zlib1g-dev 
            - libssl-dev
            - liblz4-dev
            - libcurl4-openssl-dev 
            - liblz-dev
            - libbz2-dev
      env:
         - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
      compiler: gcc

    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - pkg-config
            - libncurses5-dev
            - libncursesw5-dev
            - zlib1g-dev 
            - libssl-dev
            - liblz4-dev
            - libcurl4-openssl-dev 
            - liblz-dev
            - libbz2-dev
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
      compiler: gcc
      
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - clang-3.6
            - pkg-config
            - libncurses5-dev
            - libncursesw5-dev
            - zlib1g-dev 
            - libssl-dev
            - liblz4-dev
            - libcurl4-openssl-dev 
            - liblz-dev
            - libbz2-dev
      env:
        - MATRIX_EVAL="CC=clang-3.6 && CXX=clang++-3.6"
      compiler: clang

    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
          packages:
            - clang-3.7
            - pkg-config
            - libncurses5-dev
            - libncursesw5-dev
            - zlib1g-dev 
            - libssl-dev
            - liblz4-dev
            - libcurl4-openssl-dev 
            - liblz-dev
            - libbz2-dev
      env:
        - MATRIX_EVAL="CC=clang-3.7 && CXX=clang++-3.7"
      compiler: clang

    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.8
          packages:
            - clang-3.8
            - pkg-config
            - libncurses5-dev
            - libncursesw5-dev
            - zlib1g-dev 
            - libssl-dev
            - liblz4-dev
            - libcurl4-openssl-dev 
            - liblz-dev
            - libbz2-dev
      env:
        - MATRIX_EVAL="CC=clang-3.8 && CXX=clang++-3.8"
      compiler: clang

    # works on Trusty
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-3.9
          packages:
            - clang-3.9
            - pkg-config
            - libncurses5-dev
            - libncursesw5-dev
            - zlib1g-dev 
            - libssl-dev
            - liblz4-dev
            - libcurl4-openssl-dev 
            - liblz-dev
            - libbz2-dev
      env:
        - MATRIX_EVAL="CC=clang-3.9 && CXX=clang++-3.9"
      compiler: clang

    # works on Trusty
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-4.0
          packages:
            - clang-4.0
            - pkg-config
            - libncurses5-dev
            - libncursesw5-dev
            - zlib1g-dev 
            - libssl-dev
            - liblz4-dev
            - libcurl4-openssl-dev 
            - liblz-dev
            - libbz2-dev
      env:
        - MATRIX_EVAL="CC=clang-4.0 && CXX=clang++-4.0"
      compiler: clang

    # works on Trusty
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
            - pkg-config
            - libncurses5-dev
            - libncursesw5-dev
            - zlib1g-dev 
            - libssl-dev
            - liblz4-dev
            - libcurl4-openssl-dev 
            - liblz-dev
            - libbz2-dev
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"
      compiler: clang

    # OSX begin
    - os: osx
      osx_image: xcode10
      env:
        - MATRIX_EVAL="brew update && brew install gcc5 && CC=gcc-5 && CXX=g++-5"

    - os: osx
      osx_image: xcode10
      env:
        - MATRIX_EVAL="brew update && brew install gcc6 && CC=gcc-6 && CXX=g++-6"

    - os: osx
      osx_image: xcode10
      env:
        - MATRIX_EVAL="brew update && brew install gcc && CC=gcc-7 && CXX=g++-7"

    - os: osx
      osx_image: xcode10
      env:
        - MATRIX_EVAL="brew update && brew install gcc && CC=gcc-8 && CXX=g++-8"


before_install:
  - eval "${MATRIX_EVAL}"
  - git clone https://github.com/facebook/zstd
  - cd zstd && make -j4 && sudo make install && cd ..
  - git clone https://github.com/samtools/htslib
  - cd htslib && make && make lib-static && sudo make install && cd ..

script:
  - git submodule update --recursive
  - make -j4

